/* PDF 使用网站共享数据；静态排版独立于网页交互，不改动线上页面。 */
(function () {
  'use strict';
  const S = window.SITE;
  const ONLINE = 'https://zhou-xingyun-portfolio.vercel.app/';
  const esc = s => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
  const img = (src, alt, cls) => '<img class="' + (cls || '') + '" src="../' + esc(src) + '" alt="' + esc(alt || '') + '">';
  const link = (url, label) => '<a class="link" href="' + esc(url) + '">' + esc(label) + ' ↗</a>';
  const stat = (n, label) => '<div class="stat"><b>' + esc(n) + '</b><span>' + esc(label) + '</span></div>';
  const num = n => n.toLocaleString('en-US');
  const note = s => '<p class="note">' + esc(s) + '</p>';
  const para = s => '<p class="body">' + esc(s) + '</p>';
  const header = (tag, title, deck) => '<div class="eyebrow">' + tag + '</div><h2 class="title">' + title + '</h2>' + (deck ? '<p class="deck">' + esc(deck) + '</p>' : '');
  const pages = [];
  function page(id, title, body, cls) { pages.push({id, title, body, cls: cls || ''}); }
  const tt = S.tiktok.works;
  const ig = S.instagram.works;

  page('cover', '封面', '<div class="eyebrow">SELECTED WORKS / 2026</div><p class="identity">' + esc(S.identity.title) + ' · ' + esc(S.identity.cohort) + '</p>' + img('assets/raw/type/name-xingshu-v1.png', '周性运', 'name') + img('assets/raw/type/intro-xingshu-v1.png', S.identity.about.join(''), 'intro-art') + img('assets/raw/character/front.webp', '黏土人物肖像', 'figure') + '<div class="cover-tag">个人作品集 · PORTFOLIO</div><p class="cover-bottom">产品运营 / AI 工作流 / 内容制作 / 个人工具</p>', 'cover');

  const toc = [['cindy','01','AI 工作流与工具','cindy','photo-grade'],['tt-lead','02','短视频策划与复盘','tt-lead','tt-review'],['posters','03','视觉创意与互动','posters','reels'],['localization','04','教学内容与制作协作','localization','localization'],['hupu','05','社区长文','hupu','hupu'],['rally','06','游戏与个人账号','rally','rally'],['experience','07','经历与联系','experience','contact']];
  page('contents', '目录与代表成果', header('A QUICK LOOK', '从内容想法，到作品落地', S.identity.claim) + '<div class="toc-grid"><div><p class="body">' + esc('2027 届应用经济学硕士、数学本科。目前在心动参与 Cindy 产品运营，实践需求拆解、插件与工作流搭建、内容制作及产品反馈迭代。') + '</p><div class="proof-grid">' + stat('1.6M','TikTok · 单条视频播放') + stat('571,226','虎扑 · 单篇文章阅读') + stat('300+','开拍 RALLY · 累计玩家') + stat('19.6K','TikTok · 账号历史粉丝') + '</div><p class="note" style="margin-top:30px">以上为不同时间、不同口径的记录，详细来源见对应案例页。<br>点击目录可跳转；案例页链接可打开原作品。</p></div><nav class="toc">' + toc.map(t => '<a href="#' + t[0] + '"><b>' + t[1] + '</b><span>' + t[2] + '</span><span>' + '<span data-page-range="' + t[3] + ',' + t[4] + '"></span>' + '</span></a>').join('') + '</nav></div>');


  const P=S.projects, X=S.experience.find(e=>e.company==='心动');
  page('cindy','心动 · 产品运营与 AI 工作流',header('01 / XD · CINDY','把产品需求，变成可以使用的流程','需求拆解、AI 插件与工作流搭建、产品测试，以及用户反馈闭环。') + '<div class="cindy-layout"><div><div class="label">心动网络股份有限公司</div><h3 class="case-heading">产品运营实习生</h3><p class="body">AI Agent 产品 Cindy</p><p class="sub">' + esc(X.period) + '</p><div class="cindy-summary"><b>从问题到验收</b><p>梳理团队流程和用户场景，明确功能边界与交互方式，将需求拆成可执行的步骤。</p></div><div class="cindy-summary"><b>已投入使用</b><p>「录屏→宣传短片」自动化插件已投入团队内部使用。</p></div>' + link(ONLINE+'site/#works-ai','在线查看 AI 实践') + '</div><div>' + X.points.map((text,i)=>'<article class="cindy-duty"><span>'+['插件设计与落地','工作流自动化','产品测试与反馈','内容制作与复用'][i]+'</span><p>'+esc(text)+'</p></article>').join('') + '</div></div>' + note('后两页展示产品演示视频与动效素材库；摄影调色另列为个人工具项目。'));

  page('cindy-video','Cindy · 产品演示视频',header('01 / PRODUCT VIDEO',esc(P.video.title),P.video.description) + '<div class="ai-case-grid"><div><a href="'+ONLINE+'assets/projects/cindy/remote-camping.mp4">'+img(P.video.poster,P.video.name,'ai-video-poster')+'</a><p class="note" style="margin-top:12px">'+esc(P.video.meta)+' · 点击画面或链接观看完整视频</p>'+link(ONLINE+'assets/projects/cindy/remote-camping.mp4','观看完整视频')+note(P.video.note)+'</div><div><h3 class="small-head">独立完成的环节</h3><p class="body">'+esc(P.video.role)+'</p><div class="ai-steps">'+P.video.steps.map(x=>'<article><h3>'+esc(x.title)+'</h3><p>'+esc(x.text)+'</p></article>').join('')+'</div></div></div>');

  page('motion-atlas','动效素材库 · Motion Atlas',header('01 / MOTION ATLAS',esc(P.library.title),P.library.subtitle)+'<div class="atlas-grid"><div>'+img(P.library.image,P.library.alt,'atlas-screen')+note(P.library.note)+'</div><div><p class="body">'+esc(P.library.description)+'</p><p class="credit">'+esc(P.library.role)+'</p><div class="ai-steps">'+P.library.steps.map(x=>'<article><h3>'+esc(x.title)+'</h3><p>'+esc(x.text)+'</p></article>').join('')+'</div>'+link(ONLINE+'site/#project-motion-atlas','在线查看项目')+'</div></div>');

  page('photo-grade','摄影调色 · 个人工具',header('01 / PERSONAL TOOL',esc(P.photo.title),P.photo.subtitle)+'<div class="photo-pair"><figure>'+img(P.photo.before,P.photo.alt+'：默认显影')+'<figcaption>默认显影</figcaption></figure><figure>'+img(P.photo.styles[0].image,P.photo.alt+'：自然通透')+'<figcaption>自然通透 · 工具实际输出</figcaption></figure></div><div class="photo-pdf-copy"><div><h3 class="small-head">工作流设计与工具实现</h3><p>'+esc(P.photo.description)+'</p></div><div><h3 class="small-head">同一张照片，比较三种风格</h3><p>自然通透 / 日系胶片 / Ins 清透。在线版可切换风格，拖动分界线查看调色前后。</p>'+link(ONLINE+'site/#practice-photo','打开交互对比')+'</div></div>'+note('个人构建的 AI 应用项目。图像来自本地调色工具真实输出，PDF 展示静态对比。'));

  const lead = tt.find(w => w.id === S.tiktok.lead);
  page('tt-lead', 'TikTok · 三分王与街球传奇', '<div class="hero-case"><figure>' + img(lead.src, lead.title, 'work-img') + '</figure><div><div class="eyebrow">02 / TIKTOK · 代表案例</div><h2>' + esc(lead.title) + '</h2><p class="body">' + esc(lead.face) + '</p><div class="statrow">' + stat('1.6M','播放') + stat('103,700','点赞') + stat(lead.rate + '%','点赞 / 播放') + '</div><div class="rule"><h3 class="small-head">内容切入</h3><p class="body">球星对抗关系被映射到游戏角色上，让泛篮球用户也能快速理解画面中的对阵。</p></div><div style="margin-top:20px"><h3 class="small-head">我负责的环节</h3><p class="body">围绕账号内容完成选题、创意与脚本、素材制作与协作、成片审核、发布及数据记录。</p></div>' + link(lead.url,'观看原视频') + '<p class="note" style="margin-top:16px">' + esc(S.tiktok.note) + '<br>点赞 / 播放按公开累计数据计算，并非全量互动率。</p></div></div>');

  function ttCard(w) { return '<article><figure>' + img(w.src,w.title) + '</figure><div><div class="label">' + esc(w.cat) + '</div><h3>' + esc(w.title) + '</h3><p>' + esc(w.face) + '</p><div class="statrow">' + stat(num(w.views),'播放') + stat(num(w.likes),'点赞') + '</div>' + link(w.url,'观看原视频') + '</div></article>'; }
  page('tt-more', 'TikTok · 参与感与话题延展', header('02 / TIKTOK · 更多切入', '让观看产生参与，让话题延伸到球场外', '两条不同方向的热点二创：用二选一组织参与，用人物关系扩大理解范围。') + '<div class="case-pair">' + ttCard(tt[1]) + ttCard(tt[5]) + '</div><div class="strip"><span class="label">日常工作链路</span><br>' + S.tiktok.duties.map(d=>esc(d.name)).join(' → ') + '</div>' + note(S.tiktok.note));

  page('tt-review', 'TikTok · 数据与复盘', header('02 / TIKTOK · 数据记录', '保留表现差异，才能看见选题判断', '六条作品放在同一张表中：播放量与点赞表现分开看，避免只展示峰值。') + '<table class="table"><thead><tr><th>作品</th><th>切入方向</th><th class="num">播放</th><th class="num">点赞</th><th class="num">点赞 / 播放</th></tr></thead><tbody>' + tt.map(w=>'<tr class="' + (w.id==='TT5'?'best':'') + '"><td><a href="' + esc(w.url) + '">' + esc(w.title) + ' ↗</a></td><td>' + esc(w.cat) + '</td><td class="num">' + num(w.views) + '</td><td class="num">' + num(w.likes) + '</td><td class="num">' + w.rate + '%</td></tr>').join('') + '</tbody></table><div class="insights"><div><h3>资讯之外，需要一个可参与的关系</h3><p>Warriors 阵容话题的点赞 / 播放占比在六条中最低。后续选题更关注对阵、选择与人物关系，而不仅是信息本身。</p></div><div><h3>低播放不等于低互动占比</h3><p>Herro 与 Bam 的播放量最低，但点赞 / 播放为 ' + tt[3].rate + '%。两项指标需要分开观察，不能仅凭这组数据判断分发原因。</p></div></div><p class="note" style="margin-top:16px">' + esc(S.tiktok.note) + ' 比例仅为点赞数 ÷ 播放量；样本差异不代表因果关系。<br>' + esc(S.tiktok.account.name) + ' · 19.6K 粉丝为 2026-08-12 历史记录。</p>');

  page('posters', 'Instagram · 赛事视觉', header('03 / INSTAGRAM · 赛事节点', '把赛事热度，变成一眼读懂的视觉', S.instagram.brief) + '<div class="poster-pair">' + ig.slice(0,2).map(w=>'<article><figure>' + img(w.images[0].src,w.images[0].alt) + '</figure><div><div class="label">' + esc(w.cat) + '</div><h3>' + esc(w.title) + '</h3><p>' + esc(w.role) + '</p><div class="statrow">' + w.metrics.map(m=>stat(m.value,m.label)).join('') + '</div>' + link(w.url,'查看原帖') + '</div></article>').join('') + '</div><p class="note" style="margin-top:24px">' + esc(S.instagram.note) + '。左：本人设计与制作。右：AIGC 辅助产出，本人负责创意、版式要求与筛选。</p>');

  page('guess', 'Instagram · GUESS WHO', header('03 / INSTAGRAM · 上线预热', 'GUESS WHO：用线索组织竞猜', '把球员生涯信息转成视觉线索，让用户在新球员上线前参与猜测。') + '<div class="grid3 guess">' + ig.slice(2,5).map(w=>'<article>' + img(w.images[0].src,w.images[0].alt) + '<h3>' + esc(w.title.replace('GUESS WHO · ','')) + '</h3><p>' + esc(w.desc) + '</p>' + link(w.url,'查看原帖') + '</article>').join('') + '</div><div class="strip">职责边界：本人负责创意、草图、线索、制作 Brief 与审核；美术团队完成最终成图。</div>');

  page('reels', 'Instagram · 短视频创意', header('03 / INSTAGRAM · REELS', '把平台上的熟悉形式，接到游戏内容里', '用连续静帧展示画面表达；点击链接观看完整视频。') + ig.slice(5).map(w=>'<article class="reel-row"><div class="frames">' + w.images.map(i=>img(i.src,i.alt)).join('') + '</div><div><h3>' + esc(w.title) + '</h3><p>' + esc(w.desc) + '</p>' + link(w.url,'观看完整视频') + '<p class="note" style="margin-top:12px">' + esc(w.credit) + '</p></div></article>').join(''));

  const L=S.localization;
  page('localization','日韩 · 教学内容协作',header('04 / CONTENT OPERATIONS','给新玩家带个路',L.brief) + '<div class="local-grid"><div><div class="statrow" style="margin-top:0">' + stat(L.count.value,'条上线前教学内容规划与协作') + '</div>' + note(L.countNote) + img(L.capture.src,L.capture.alt,'evidence') + note(L.capture.caption) + link(L.accountUrl,L.accountLabel) + '</div><div>' + L.steps.map(s=>'<div class="step"><b>' + s.n + '</b><div><h3>' + esc(s.name) + '</h3><p>' + esc(s.text) + '</p></div></div>').join('') + '<div class="credit">' + esc(L.credit) + '</div></div></div>');

  const H=S.hupu;
  page('hupu','虎扑 · 社区长文',header('05 / SPORTS COMMUNITY','从一个问题，展开一篇讨论',H.role) + '<div class="grid2">' + H.articles.map(a=>'<article class="article"><div class="cat">' + a.n + ' / ' + esc(a.cat) + '</div><h3>' + esc(a.title) + '</h3><p>' + esc(a.desc) + '</p><div class="statrow">' + stat(num(a.views),'阅读') + stat(num(a.replies),'回复') + '</div>' + link(a.url,'阅读全文') + '</article>').join('') + '</div><p class="note" style="margin-top:32px">' + esc(H.note) + '。PDF 展示选题与摘要，完整正文见原帖。</p>');

  const R=S.practice.rally;
  page('rally','个人项目 · 开拍 RALLY',header('06 / PERSONAL PRACTICE','没人要求我做的部分',R.intro) + '<div class="rally"><div>' + img(R.visual.src,R.visual.alt) + note(R.visual.caption) + link(R.play,'打开游戏') + '　' + link(R.code,'查看源码') + '<div class="strip"><span class="label">持续的内容练习 / 抖音「詹库侠」</span><p style="font-size:17px">' + esc(S.practice.douyin.desc) + '</p>' + link(S.practice.douyin.url,'查看个人账号') + '</div></div><div><h3>从个人需求开始</h3><p>' + esc(R.story[0].text) + '</p><div class="rule" style="margin-top:20px"><h3>用 AI 把想法落地，再边玩边改</h3><p>' + esc(R.story[1].text) + '</p></div><div class="statrow">' + stat('300+','上线近一周累计玩家') + '</div>' + note(R.story[2].source) + '<p class="note" style="margin-top:12px">支持人机练习与双手机好友实时 1V1。</p></div></div>');

  page('experience','教育与实习经历',header('07 / BACKGROUND','从内容运营，到产品与工具实践','心动产品运营见第 3 页；此前在网易、虎扑与盛力世家积累内容和现场协作经验。') + '<div class="experience"><div><div class="label">教育背景</div>' + S.education.map(e=>'<article class="edu"><div class="sub">' + esc(e.period) + '</div><h3>' + esc(e.school) + '</h3><p>' + esc(e.major) + '</p></article>').join('') + '<div class="rule" style="margin-top:20px"><p class="body">数学本科与应用经济学硕士背景；把对体育的兴趣，延伸到内容、社区和产品实践。</p></div></div><div>' + S.experience.filter(e=>e.company!=='心动').map(e=>'<article class="job"><div><h3>' + esc(e.company) + '</h3><div class="sub" style="margin-top:10px">' + esc(e.period) + '</div></div><div><h4>' + esc(e.role) + '</h4><p>' + e.points.map(esc).join(' · ') + '</p></div></article>').join('') + '</div></div>');

  page('contact','联系与在线作品', '<div class="eyebrow">LET’S TALK</div><div class="contact-layout"><div><h2>来找我聊聊。</h2><p class="body">' + esc(S.contact.lead) + '</p><a class="email" href="mailto:' + esc(S.contact.email) + '">' + esc(S.contact.email) + ' ↗</a><div class="contact-links"><a href="tel:' + S.contact.phone + '">' + S.contact.phoneDisplay + '</a><a href="' + S.contact.githubUrl + '">GitHub ↗</a></div>' + link(ONLINE + S.contact.resume.src,'下载最新简历') + '<p class="note">简历文件更新于 2026-09-25。<br>作品数据沿用各页注明的记录时间，不代表实时数值。<br>PDF 更新于 2026-10-08。</p></div><div class="qr-wrap"><a href="' + ONLINE + '"><img class="qr" src="website-qr.png" alt="在线作品集二维码"></a><h3 class="small-head">完整在线作品集</h3><p class="note">扫码打开网站，体验交互、<br>观看原作品与个人项目。</p>' + link(ONLINE,'打开网站') + '</div></div>');

  document.getElementById('pages').innerHTML = pages.map((p,i)=>'<section class="page ' + p.cls + '" id="' + p.id + '" data-title="' + esc(p.title) + '"><div class="running"><span>周性运 / LUCKY</span><span>产品运营 · 内容策划 · AI 应用实践</span></div>' + p.body + '<footer class="footer"><a href="#contents">目录 ↗</a><span>SELECTED WORKS · 2026</span><span>' + String(i+1).padStart(2,'0') + ' / ' + pages.length + '</span></footer></section>').join('');
  document.querySelectorAll('[data-page-range]').forEach(node=>{const [start,end]=node.dataset.pageRange.split(',').map(id=>pages.findIndex(p=>p.id===id)+1);node.textContent=String(start).padStart(2,'0')+(start===end?'':'—'+String(end).padStart(2,'0'));});
  window.PDF_CHAPTERS = pages.map(p=>({id:p.id,title:p.title}));
}());
